version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"