POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Produto 1",
  "price": 100.0
}

###
GET http://localhost:8080/products/90083dee-3d26-4557-8ad5-3c017d9f809c
Content-Type: application/json

###
PUT http://localhost:8080/products/90083dee-3d26-4557-8ad5-3c017d9f809c
Content-Type: application/json

{
  "name": "Produto 1",
  "price": 400.0
}

###
DELETE http://localhost:8080/products/90083dee-3d26-4557-8ad5-3c017d9f809c
Content-Type: application/json

###
GET http://localhost:8080/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvdWx1YW5mQGljbG91ZC5jb20iLCJleHAiOjE2ODA3MzQ4NjUsInN1YiI6IjRjNzJmNTMzLTg2MzYtNGJjZi04MWMwLWM1NWI4Njc4ZWVhYiJ9._8KfhIPSQj0Ui0fzU0p9ivxARbRzbtR0mya7CkjXy-U

###
GET http://localhost:8080/products?page=1&limit=2&sort=asc
Content-Type: application/json