POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
  "name": "Luan Fernandes",
  "email": "souluanf@icloud.com",
  "password": "123456"
}

###
POST http://localhost:8080/users/generate_token HTTP/1.1
Content-Type: application/json

{
  "email": "souluanf@icloud.com",
  "password": "2056"
}


###
PUT http://localhost:8080/products/90083dee-3d26-4557-8ad5-3c017d9f809c
Content-Type: application/json

{
  "name": "Produto 1",
  "price": 400.0
}

###
DELETE http://localhost:8080/products/90083dee-3d26-4557-8ad5-3c017d9f809c
Content-Type: application/json

###
GET http://localhost:8080/products
Content-Type: application/json

###
GET http://localhost:8080/products?page=1&limit=2&sort=asc
Content-Type: application/json